home:
    path: /
    defaults: { _controller: 'App\Controller\HomeController:index' }

game:
    path: /jeu
    controller: App\Controller\HomeController:play

## request AJAX
chess_enabled_moves:
    path: /jeu/enabled_moves
    controller: App\Controller\ChessController:enabledMoves

chess_move:
    path: /jeu/move
    controller: App\Controller\ChessController:move